In [14]:
# 문제 1
import numpy as np
'''
아래와 같은 원소들을 갖도록 두 numpy 배열 a, b를 각각 선언하세요.
a = [1,2,3,4]
b = [5,6,7,8]
'''

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# 아래 연산들을 수행하고, 그 결과를 출력하세요.

#1. a와 b의 요소 곱(element-wise product)을 계산하고 출력하세요.
print(a*b)
#2. a와 b의 내적(dot product)을 계산하고 출력하세요.
print(np.dot(a,b))
#3. a와 b의 요소 평균(mean)을 계산하고 출력하세요. 
print(np.mean(a), np.mean(b))
#4. a와 b의 요소 표준편차(standard deviation)를 계산하고 출력하세요.
print(np.std(a), np.std(b))
#5. a의 shape을 2x2로 변경하고, shape이 변경된 배열과 shape을 각각 출력하세요.
print(a.reshape(2,2))
print(np.shape(a))

[ 5 12 21 32]
70
2.5 6.5
1.118033988749895 1.118033988749895
[[1 2]
 [3 4]]
(4,)


In [62]:
# 문제 2

import numpy as np

# 1. 랜덤하게 채워진 (3, 4) shape의 Numpy 배열 선언하고 출력하세요.
x = np.random.randint(0,100,(3,4))
print(x)
# 2. 선언한 배열에서 최댓값을 찾아서 출력하세요. 
print(max(map(max,x)))
# 3. 선언한 배열에서 최솟값을 찾아서 출력하세요.
print(min(map(min,x)))
# 4. 배열의 두 번째 열(column)의 원소를 가져와서 출력하세요.
print(x[:,1])
# 5. 배열의 세 번째 행(row)의 원소를 가져와서 출력하세요.
print(x[2,:])
# 6. 배열의 첫 번째 행(row)에서 앞에서 두 개의 원소까지만 slicing 해서 출력하세요.
print(x[0,:2])
# 7. 선언한 배열의 요소 중 모든 짝수를 0으로 대체하고, 그 결과를 출력하세요.
cnt=0
for i in range(len(x)):
    for j in range(len(x[i])):
        if(x[i][j] % 2 == 0):
            x[i][j] = 0
print(x)

[[57 31 90 68]
 [40 24 18 51]
 [47 20 41 70]]
90
18
[31 24 20]
[47 20 41 70]
[57 31]
[[57 31  0  0]
 [ 0  0  0 51]
 [47  0 41  0]]
